APP_NAME = "JOSM Tagger"
APP_VERSION = "0.1.14.00"
APP_AUTHOR = "By Max1234-ITA, 2026"
APP_INFO = f"{APP_NAME} v.{APP_VERSION}\n- {APP_AUTHOR} -"

APP_REPOSITORY_URL = "https://github.com/Max1234-Ita/Josm_Tagger"
GITHUB_REPOSITORY_OWNER = "Max1234-Ita"
GITHUB_REPOSITORY_NAME = "Josm_Tagger"
